### PR TITLE
Fix Typo in README.MD

### PR DESCRIPTION
**Pull request by FrostyPenguin**
Fixed a typo in `Legal stuff`

> read careful **ly**

…

> before distributing **[…]** any part

### CODE REVIEW

**Comment by Legimet** [comment]
You can also remove the "on a different server for now" before the Hackspire link.

**Comment by FrostyPenguin** [comment]
@Legimet OK, I've removed it.

**Comment by Vogtinator** [comment]
Thanks!
I'd change ```Please read carefully the file "Mozilla-Public-License-v1.1.html" before [...]``` to ```Please read the file "Mozilla-Public-License-v1.1.html" carefully before [...]``` though.

**Comment by FrostyPenguin** [comment]
I thought about changing that, too, but I didn't want to alter the file too much.
It's great to hear that someone else thinks this sentence should be rephrased :grin:

**Comment by FrostyPenguin** [comment]
@Vogtinator Updated.

**Pull request merged**
