### PR TITLE
Rename `sleep` to `msleep`

### LINKED ISSUE #142: Regarding the `sleep` function in libndls
The sleep function in `ndless-sdk/libndls/sleep.c` currently maps to the POSIX `sleep` function defined in `unistd.h`, however the standard defines that function to accept an argument in seconds, and the one in `sleep.c` takes an argument in milliseconds. I understand that that would be a breaking change, but it would be more standards compliant for that to be a different function, perhaps something like `msleep`, while `sleep` would just be `msleep(seconds * 1000)`.

### PR DESCRIPTION
**Pull request by coolreader18**
`sleep` by default has the same behavior as before, but one can set `LIBNDLS_POSIX_SLEEP` to true, and it will switch to using sleep as the POSIX standard defines it. That way, if you're using a shared library that utilizes `sleep`, you can voluntarily switch over to using the POSIX behavior, and adjust your code to use `msleep`. Perhaps eventually, the new behavior could be the default.

Resolves #142.

### CODE REVIEW

**Comment by Vogtinator** [comment]
IMO using a global variable to change behaviour at runtime is a bad idea - it can result in surprises.

That's why I suggested to just remove `sleep` for now. Alternatively, define sleep as a macro and raise a helpful error message, like it's done for `SCREEN_BASE_ADDRESS`.

**Comment by Vogtinator** [comment]
IMO using a global variable to change behaviour at runtime is a bad idea - it can result in surprises.

That's why I suggested to just remove `sleep` for now. Alternatively, define sleep as a macro and raise a helpful error message, like it's done for `SCREEN_BASE_ADDRESS`.

**Comment by coolreader18** [comment]
Alright, will do.

**Comment by Vogtinator** [comment]
LGTM so far, just two remaining issues:

Several samples still use `sleep`, can you change that to `msleep`?

It needs to be `#define sleep(x) ...` to make sure that `int sleep = 30;` won't fail.

**Comment by coolreader18** [comment]
What do you mean by examples? As far as I can tell there's no documentation in the repository.

**Comment by coolreader18** [comment]
Ah, never mind, I see what you meant.

**Comment by coolreader18** [comment]
By the way, I think some of the samples were outdated; one said that `msleep` wasn't compatible with `!is_classic`, and there were a bunch of other errors in my IDE.

**Comment by Vogtinator** [comment]
> By the way, I think some of the samples were outdated; one said that msleep wasn't compatible with !is_classic,

Which one? 

> and there were a bunch of other errors in my IDE.

I don't get any errors here.

**Comment by Vogtinator** [comment]
Please remove the `_sleep` macro redirection in `libndls.h`, AFAICT that's unnecessary.

I just fixed nSDL - I'll push the binary here once this is merged.

**Comment by coolreader18** [comment]
Whoops, it wasn't in a sample, it was in [stage2 of the the 3.6 installer](https://github.com/ndless-nspire/Ndless/blob/d6a5f68ef27400ebe30ab0b8cbe65c361bf48de4/ndless/src/installer-3.6/stage2.cpp#L99). I was just grepping through the project directory for samples to change, and I guess I thought it was a sample too.

It could be the way my IDE is configured that I'm getting the errors. Stuff like identifiers being undefined, so it could be looking in the wrong search path for header files.

**Pull request merged**
