### PR TITLE
Some fixes and improvements

### PR DESCRIPTION
**Pull request by Vogtinator**
Now split from #202 as the lcd compatibility mode has to be fixed for CX HW-AA+ first.

See commits for details.

### CODE REVIEW

**Comment by Vogtinator** [comment]
Binary built from this PR: [ndless_resources.zip](https://github.com/ndless-nspire/Ndless/files/4294323/ndless_resources.zip)

**Comment by Vogtinator** [comment]
Confirmed to work on reddit: https://old.reddit.com/r/nspire/comments/fdidbs/lua_doesnt_work_with_ndless_installed/fjlx3r4/

**Comment by RedshiftVelocities** [comment]
Wait, confirmed to work on 4.5.1?? I thought Ndless wasn't compatible with the newer versions yet.

**Comment by adriweb** [comment]
Ndless has been compatible with 4.5.1 for a while, just not the installer itself. You'd need an other/external installer that only works on some hardware versions.

**Comment by RedshiftVelocities** [comment]
Aha, thanks. Where can I find this external installer (or does it not exist)?

**Pull request merged**
