### PR TITLE
More flexible code

### PR DESCRIPTION
**Pull request by Ti64CLi**

### CODE REVIEW

**Comment by Vogtinator** [comment]
Is there anything in here which isn't covered by #211? I'm planning to merge that (again) today.

**Comment by Ti64CLi** [comment]
I think so yes.
I added some if statements for downloaded detection.
Maybe it's useless, but I think it could be useful when you don't to extract everything again

**Comment by Vogtinator** [comment]
#211 does that as well, but without needing flag files and it will also work correctly after version bumps. So I'll close this now.

**Comment by Ti64CLi** [comment]
Ok, I didn't see it, sorry

**Pull request closed without merging**
