### PR TITLE
Use relative paths from the dynamic virtual root

### PR DESCRIPTION
**Pull request by adriweb**
## Quick summary of the advantages of this

* Cheaters won't be able to cheat with startup programs when in PTT, while the standard users (non-cheaters) will be unaffected  
Side-effect: TI and teachers may see that Ndless, and by extension the Ndless team, is not on the side of cheaters - _native programming should not be seen as worrisome_
* Cleaner and more reliable code (less hard-coded "magic" strings etc.)
* If, for some reason, TI changes the virtual root names/paths, everything wouldn't be broken anymore
* Simplified coding for developers already having to take care of this issue manually
* While in PTT and with access to a computer (i.e. not while taking an exam), it's now easier to install Ndless, thus helping to solve potential BootD corruption issues

## Tests
_We're assuming there's a valid /documents/ndless/ folder with the required files in it_
**Legend**: W = Works, F = Fails (combined with ✓ = OK (as expected), ✗ = bad (not as expected/bug)).
<table>
<tr><td rowspan="2" colspan="2"></td><td colspan="2"><b>OS 4.4</b></td><td colspan="2"><b>OS 4.2</b></td><td colspan="2"><b>OS 4.0</b></td><td colspan="4"><b>OS 3.9.0/1</b></td><td colspan="4"><b>OS 3.6</b></td></tr>
<tr><td><b>CX</b></td><td><b>CX CAS</b></td><td><b>CX</b></td><td><b>CX CAS</b></td><td><b>CX</b></td><td><b>CX CAS</b></td><td><b>CX</b></td><td><b>CX CAS</b></td><td><b>non-CAS</b></td><td><b>CAS</b></td><td><b>CX</b></td><td><b>CX CAS</b></td><td><b>non-CAS</b></td><td><b>CAS</b></td></tr>
<tr><td rowspan="2"><b>All-files ndless install</b><br/><i>(+ prgm launch, ext support...)</i></td><td><b>Normal</b></td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td></td><td></td><td>W ✓</td><td>W ✓</td><td></td><td></td></tr>
<tr><td><b>In PTT</b></td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td>W ✓</td><td></td><td></td><td>W ✓</td><td>W ✓</td><td></td><td></td></tr>
<tr><td rowspan="2"><b>Installer-only ndless install</b></td><td><b>Normal</b></td><td colspan="14" align="center"><i>N/A</i></td></tr>
<tr><td><b>In PTT</b></td><td>F ✓</td><td>F ✓</td><td>F ✓</td><td>F ✓</td><td>F ✓</td><td>F ✓</td><td>F ✓</td><td>F ✓</td><td></td><td></td><td>F ✓</td><td>F ✓</td><td></td><td></td></tr>
<tr><td rowspan="2"><b>Automatic ndless install</b><br/><i>(using nLaunchy/etc.)</i></td><td><b>Normal</b></td><td></td><td>W ✓</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>W ✓</td><td></td><td></td><td></td></tr>
<tr><td><b>In PTT</b></td><td></td><td>W ✓</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>F ✓</td><td></td><td></td><td></td></tr>
<tr><td rowspan="2"><b>Startup program behaviour</b></td><td><b>Normal</b></td><td></td><td>W ✓</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>W ✓</td><td></td><td></td><td></td></tr>
<tr><td><b>In PTT</b></td><td></td><td>F ✓</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>F ✓</td><td></td><td></td><td></td></tr>
</table>

Please submit your own tests results, hopefully for more parameters (nLaunch/nLaunchy/ControlX, on Classic calculators, more OSes...)
[ndless_pr_64.zip](https://github.com/ndless-nspire/Ndless/files/835714/ndless_pr_64.zip)

### CODE REVIEW

**Comment by adriweb** [comment]
Alright, I've successfully completed the 4.0, 4.2, 4.4 tests in normal+PTT for the ndless install check (no regression).
Bisam contributed the automatic install behaviour on his non-CAS CX 3.6, successfully as well.
I'll try 3.9 and 3.6 on my CX / CX CAS, but I guess this is all good.

**Comment by adriweb** [comment]
@Vogtinator the installer on 3.9.1 CX and CX CAS reports "ndless_resources not found" while working everywhere else.
Could it be that the get_documents_dir syscall address is wrong for this OS?

**Comment by critor** [comment]
1st test with ControlX (4.4.3 RC2) and OS 4.4 CAS.
As expected.

In exam mode :
- Ndless is installed
- but /documents/ndless/startup/ programs aren't launched

And in normal mode :
- Ndless is installed
- /documents/ndless/startup/ programs are launched

**Comment by adriweb** [comment]
Thanks, table updated.

**Comment by critor** [comment]
Thanks.

Small error then, in PTT mode Ndless automatic installation works.
But it's as expected, and it's not really a problem since startup programs won't be available without an USB onnection.

**Comment by adriweb** [comment]
Hm, right. But yes, as long as nothing is launched (since there is nothing to launch), it is fine.

**Comment by Vogtinator** [comment]
The 3.9.1 syscall addresses look good to me, I'll have a closer look later. Can you verify the issue with any other ndless program?

**Comment by adriweb** [comment]
Yeah, will try.

**Comment by adriweb** [comment]
Weirdly enough, the following code runs fine on CX CAS 3.9.1:
```c
#include <nucleus.h>
#include <os.h>

#define RES_PATH_REL "./ndless/ndless_resources.tns"

int main()
{
    const char* docsdir = get_documents_dir();

    show_msgbox("docs dir", docsdir);

    NU_Set_Current_Dir(docsdir);

    NUC_FILE *res_fp = fopen(RES_PATH_REL, "rb");

    if (res_fp)
    {
        show_msgbox("res_fp ok", "good");
        fclose(res_fp);
    } else {
        show_msgbox("res_fp null", "bad");
    }

    return 0;
}
```

So, I'm not sure what's wrong in the installer...

**Comment by adriweb** [comment]
Since things are behaving correctly but something is getting overwritten during the install, I've switched to an alternate way, for the 3.9.x installer (full path building), which works fine.
Table and download updated.

**Pull request merged**
