### PR TITLE
Use submodules for zlib and freetype

### PR DESCRIPTION
**Pull request by Legimet**
Freetype is updated to the latest version of 2.6.2 from whatever it was before.

Also, Some changes are made to the nspire-* and arm-none-eabi-ld.gold wrappers so that directories supplied by -I or -L are searched before the default directories (this is the normal behavior of GCC)

And finally, a bugfix so that Ndless builds successfully in a directory containing spaces.

### CODE REVIEW

**Comment by Vogtinator** [comment]
Have you done a clean rebuild to confirm that nothing breaks?
The wiki should also be updated to mention the submodules.

**Comment by Legimet** [comment]
Yes, a clean build works as expected. I also added nspireio (your fork) as a submodule.
I can update the wiki page.

**Comment by Vogtinator** [comment]
Ok, thanks!

**Comment by Legimet** [comment]
I forgot to remove libnspireio.a from the repo, but I won't make a new PR for that :)

**Pull request merged**
