### PR TITLE
Add realpath function

### PR DESCRIPTION
**Pull request by Legimet**
From FreeBSD. I removed the symlink stuff.

### CODE REVIEW

**Comment by Vogtinator** [comment]
Where's the declaration for realpath? It doesn't add any to the includes in ndless-sdk.

**Comment by Legimet** [comment]
It's in Newlib's stdlib.h.

**Comment by Vogtinator** [comment]
newlib has a readlink.c as well, but only builds it if the target is linux, could that maybe be used instead? I'd like to avoid code duplication as much as possible.

Did you also try resolving "."? libsyscall only implements `getwd`, but realpath uses `getcwd`, which newlib doesn't have a wrapper calling getwd for, according to a quick search.

**Comment by Legimet** [comment]
> newlib has a readlink.c as well, but only builds it if the target is linux, could that maybe be used instead? I'd like to avoid code duplication as much as possible.

I assume you mean realpath. The version in Newlib has some problems. It resolves "..", "../", "/.", "//", and "///" to an empty string, and it also doesn't work when `resolved_path` is NULL (it should allocate a buffer with malloc).

> Did you also try resolving "."? libsyscall only implements getwd, but realpath uses getcwd, which newlib doesn't have a wrapper calling getwd for, according to a quick search.

Newlib does have getcwd, actually. It's located in newlib/libc/unix/getcwd.c. I'm pretty sure that "." resolves correctly, but I'll check again.

**Comment by Vogtinator** [comment]
> I assume you mean realpath. The version in Newlib has some problems. It resolves "..", "../", "/.", "//", and "///" to an empty string, and it also doesn't work when resolved_path is NULL (it should allocate a buffer with malloc).

Great... Can you report that upstream?

> Newlib does have getcwd, actually. It's located in newlib/libc/unix/getcwd.c. I'm pretty sure that "." resolves correctly, but I'll check again. EDIT: Yes, it works.

If it really uses that version, that's awful. It doesn't use getwd, it does opendir("..")/readdir/closedir to find out what . is, using the st_ino part of stat...

**Comment by Legimet** [comment]
> Great... Can you report that upstream?

Sure, I will do that.

> If it really uses that version, that's awful. It doesn't use getwd, it does opendir("..")/readdir/closedir to find out what . is, using the st_ino part of stat...

I was mistaken, the getcwd from Newlib isn't built at all, and there is a getcwd in stubs.c, so this isn't an issue. (But I agree with you about Newlib's getcwd. And there is a getwd in the Linux directory that is a wrapper around that version of getcwd!)

**Comment by Vogtinator** [comment]
Right, I totally forgot about the autogenerated headers. Should be fine then.

**Pull request merged**
